FROM scratch
MAINTAINER \
[Adam Miller <maxamillion@fedoraproject.org>] \
[Patrick Uiterwijk <patrick@puiterwijk.org>]
ENV DISTTAG=f26container FGC=f26 FBR=f26
ADD fedora-26-aarch64-20180307.tar.xz /
