language: bash
services: docker

env:
  - VERSION=jdk8
  - VERSION=jre8
  - VERSION=jdk11
  - VERSION=jre11
  - VERSION=jdk13
  - VERSION=jre13

before_install:
  - env | sort
  - cd "${VERSION}${VARIANT:+-$VARIANT}"
  - image="groovy:${VERSION}${VARIANT:+-$VARIANT}"
  - docker rmi "${image}" || true
  - docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f
  - docker images --format "table {{.Repository}}:{{.Tag}}" | tail --lines=+2 | grep "openjdk" | xargs --no-run-if-empty --max-lines=1 docker pull

install:
  - docker build --tag "${image}" .

script:
  - cd ../test
  - ./run.sh "${image}" "3.0.0-beta-2"
