.TH "ORIENTDB" "1" "" "Roberto Franchini - r.franchini@orientdb.com" "October 20, 2016"  ""


.SH NAME
.PP
orientdb \- orientdb container image


.SH DESCRIPTION
.PP
The OrientDB image provides a containerized packaging of the OrientDB multi\-model database.
OrientDB is a 2nd Generation Distributed Graph Database with the flexibility of Documents in one product.
It is a unique, true multi\-model DBMS equipped to tackle today’s big data challenges and offers multi\-master replication,
sharding as well as more flexibility for modern, complex use cases.

.PP
You can find more information on the OrientDB project from the project Web site (
\[la]http://www.oorientdb.com\[ra]).


.SH USAGE
.PP
Describe how to run the image as a container and what factors might influence the behaviour of the image
itself. For example:

.PP
To set up the host system for use by the OrientDB container, run:

.PP
atomic install orientdb

.PP
To run the XYZ container (after it is installed), run:

.PP
atomic run orientdb

.PP
To remove the OrientDB container (not the image) from your system, run:

.PP
atomic uninstall orientdb

.PP
To upgrade the OrientDB container from your system, run:

.PP
atomic upgrade orientdb
