FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f30-updates-candidatecontainer FGC=f30-updates-candidate FBR=f30-updates-candidate
ADD fedora-30-updates-candidate-x86_64-20200218.tar.xz /
CMD ["/bin/bash"]